server:
  port: 10000

sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  routes:
    translation-tool:
      path: /rest/translation-tool/**
      serviceId: translation-tool
      
---            
spring:  
  profiles: development
  
# increase of default timeouts for ribbon (will be useful for dev environment - e.g. debug)
translation-tool:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000

# increase of default timeouts for hystrix globally (will be useful for dev environment - e.g. debug)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000



  