spring:
  profiles:
    active: development
---

spring:
  profiles: development
server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tms_tst_db
    username: tms_tst_user
    password: tms1

logging:
  level:
    org:
      springframework: INFO
    com:
      wktsslot:
        translationservice: INFO